import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import Footer from "@/components/Footer";
import {CartContextProvider} from "@/context/AppContext";
import ReactQueryProvider from "@/components/ReactQueryProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Flaming Moth",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReactQueryProvider>
					<CartContextProvider>
						<NavBar />
						{children}
						<Footer />
					</CartContextProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
